version: '3'
services:
    www:
        build: .
        container_name: www
        volumes:
            - ./www:/www
        links:
            - mongodb
            - mysql
        depends_on:
            - mongodb
            - phpmyadmin
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./dump:/dump
        ports:
            - 27017:27017
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - ./dump/scriptSales100K.sql:/docker-entrypoint-initdb.d/Sales100K.sql
        environment:
            MYSQL_DATABASE: Sales100K
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        depends_on:
            - mysql