version: '3'
services:
    www:
        build: .
        volumes:
            - ./www:/www
        links:
            - mongodb
            - mysql
        depends_on:
            - mongodb
            - phpmyadmin
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27020:27017
    mysql:
        image: mysql
        restart: always
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: scriptSales100K
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - mysql:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        depends_on:
            - mysql