version: '3'
services:
    node:
        build: .
        container_name: node
        volumes:
            - ./app:/app
        command: bash -c "while ! curl -s mysql:3306 > /dev/null; do echo waiting for mysql:3306; sleep 3; done; node /app/index.js"
        links:
            - mongodb
            - mysql
        depends_on:
            - mongodb
            - mysql
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./dump/fulldb05-02-2019 19-51.json:/docker-entrypoint-initdb.d/dump/fulldb05-02-2019 19-51.json
            - ./dump/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        ports: 
            - 3306:3306
        volumes:
            - ./dump/fulldb05-02-2019 19-51.sql:/docker-entrypoint-initdb.d/fulldb05-02-2019 19-51.sql
        environment:
            MYSQL_DATABASE: Benchmark
            MYSQL_ROOT_PASSWORD: rootpass
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links: 
    #         - mysql:db
    #     ports:
    #         - 8080:80
    #     environment:
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: test
    #         MYSQL_ROOT_PASSWORD: test
    #     depends_on:
    #         - mysql